#!/usr/bin/env bash

# Basic
alias c="clear" # Clean terminal
alias q="exit" # Exit terminal
alias quit="q" # Exit terminal
alias r="refreshMyBash --verbose" # Refresh terminal with MyBash changes
alias ch="commandHistory" # Select a command from history

# Files and directories
alias l="ls -CF" # Show files and directories
alias la="ls -A" # Show all files and directories
alias ll="ls -alF" # Show files and directories with information
alias watch="tail -f" # Watch file changes

# System
alias sp="htop" # Show system process
alias ss="sudo shutdown" # Shutdown system
alias sr="sudo reboot" # Reboot system

# Routed (windows)
alias cdd="cd /mnt/d" # Go to volume D
alias cdc="cd /mnt/c" # Go to volume C
alias cde="cd /mnt/e" # Go to volume E
alias cdw="cd /mnt/c/Users/maike" # Go to windows home
alias cdmb="cd $MYBASH" # Go to mybash configuration

# Network
alias ip="curl ifconfig.me" # Show your public ip
alias ipa="sudo systemctl enable fail2ban" # Enable ip ban of fail2ban on startup
alias ipbl="sudo fail2ban-client status sshd" # Show banned ip of fail2ban
alias ipba="sudo fail2ban-client set sshd unbanip" # Add banned ip of fail2ban (ipba 192.168.1.0)

# My Aliases
alias a="myAliases" # Find and select alias (short version)
alias aliases="a" # Find and select alias
# show: aliases -s # Show and select alias
# show: aliases -f # Show my aliases file
# show: aliases -e # Edit my aliases file

# Git config
alias cn="createGitConfig" # Create git config for a specific project in volume D (cn myproject)
alias cr="vi ~/.gitconfig" # Edit gitconfig routing file
alias cg="vi $MYBASH/gitconfig/.global" # Edit global gitconfig file

# Git
alias ga="git add ." # Git add
alias gc="git commit" # Git commit
alias gca="git commit --amend" # Git commit in amend mode
alias gce="npx gitmoji-cli -c " # Git commit with emoji (npx: carloscuesta/gitmoji-cli)
alias gl="git log --pretty=format:'%C(yellow)%h%C(reset)%C(magenta) 👤 %aN %C(dim)<%ae>%C(reset) %C(blue)(%ad)%C(reset):%n%s%n'" # Git log
alias gls="git log --graph  --pretty=format:'%C(magenta)👤 %aN %C(blue)(%ar)%C(reset): %s'" # Git log with short date
alias glf="git log" # Git log with full information
alias gs="gitStatusWithWorkspaceInfo" # Git status
alias gst="git stash" # Git stash
alias gsp="git stash pop" # Git stash pop (recupera los cambios y los elimina del stash)
alias gsa="git stash apply" # Git stash apply (recupera los cambios pero lo mantiene del stash)
alias gps="git push" # Git push
alias gpl="git pull" # Git pull
alias gf="git fetch" # Git fetch
alias gt="git tag -n" # Git list tags
alias gw="getWorkspaceInfo"  # Git workspace details
alias gr="npx git-reporter"  # Git reporter for current project (npx: ulisesantana/git-reporter)

# Node
alias ni="npm install" # Npm install
alias nci="npm install" # Npm clean install
alias nid="npm install --save-dev" # Npm install in dev dependencies
alias nri="npmReinstall" # Npm reinstall dependencies
alias nr="npm run" # Npm run (Print all npm scripts)
alias nd="npm run dev" # Npm dev
alias ns="npm start" # Npm start
alias nb="npm build" # Npm start
alias nl="npm run lint" # Npm lint
alias nlf="npm run lint:fix" # Npm lint with fix
alias nt="npm test" # Npm test
alias ntw="npm run test:watch" # Npm test watching

# PHP
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail' # Laravel sail

# Docker
### Si no funciona sin sudo -> https://docs.docker.com/engine/install/linux-postinstall/
alias d="docker" # Docker
alias dps="docker ps" # Docker ps
alias dpsp="docker ps --format 'table {{.Names}}	->	{{range (split .Ports \", \")}}{{print \"	\"}}{{println .}}{{print \"		\"}}{{end}}'" # Docker ports
alias dc="docker container ls" # Docker containers
alias di="docker image ls" # Docker images
alias dv="docker volume ls" # Docker volumes
alias dcu="docker compose up -d " # Docker compose up
alias dcd="docker compose down" # Docker compose down
alias dcr="dcd && dcu" # Docker compose restart

# SSH
alias h="showSSH" # Select and connect to ssh host (short)
alias hosts="h" # Select and connect to ssh host
# show: hosts -e # Edit ssh hosts
# show: hosts -s # Show ssh hosts
alias hs="sudo systemctl status ssh" # Show ssh status
alias hst="sudo systemctl start ssh" # Start ssh
alias hr="sudo systemctl restart ssh" # Restart ssh
alias he="sudo systemctl enable ssh" # Enable ssh on startup
alias hrf="sudo mkdir -p -m0755 /var/run/sshd && systemctl restart ssh.service" # Restart ssh service forced

# Manage disks
alias md="sudo mount /dev/sda" # Mount disk + folder on mount (md /storage)
alias mdf="sudo mount -t ntfs-3g /dev/sda" # Mount disk in NFTS-3G format + folder on mount (mdf /storage)

# IDE
alias idea="intellij-idea-community" # Open IntelliJ IDEA

# Plugins
alias j="z" # Jump to folder (plugin: agkozak/zsh-z)
alias f="fzf" # Finder with selectable (plugin: junegunn/fzf)
