#!/bin/bash

# Git config
createGitConfig() {
  local CONFIGDIR=$MYBASH/.gitconfig
  local CONFIGFILE=.$@
  local PROJECTDIR=~/projects/$@/

  if ! test -f $CONFIGDIR/$CONFIGFILE; then
    echo "\n[includeIf \"gitdir:$PROJECTDIR\"]"   >> $CONFIGDIR/.global
    echo "  path = ./$CONFIGFILE"                 >> $CONFIGDIR/.global
    echo "Global gitconfig updated"
    
    echo "[user]"                                 >> $CONFIGDIR/$CONFIGFILE
    echo "  email = email@example.es"             >> $CONFIGDIR/$CONFIGFILE
    echo "New $CONFIGFILE gitconfig created"
  fi
}
