#!/bin/bash

# Git status with workspace info
gitStatusWithWorkspaceInfo() {
  local STATUS=`git status 2>&1 > /dev/null`

  if [[ "$STATUS" == *"not a git repository"* ]]; then
    echo "\e[41m Git is not initialized or you are not in a repository folder \e[0m"
  else
    getWorkspaceInfo
    echo '\n\e[36m✍️ Git status\e[0m'
    git status -sb
  fi
}
