#!/bin/bash

# Refresh my bash
refreshMyBash() {
  local ignoredFiles=("." ".." ".init" "install.sh" "README.md" ".gitignore" ".gitmodules")
  local folders=("/" "/scripts" "/plugins")

  for folder in $folders; do
    for file in $(ls -ap $MYBASH$folder | grep -v /); do
      if [[ ! $ignoredFiles[*] =~ $file ]]; then
        source $MYBASH$folder/$file
        if [[ $@ == '--verbose' ]]; then
          echo "$MYBASH$folder/$file file updated"
        fi
      fi
    done
  done
  if [[ $@ == '--verbose' ]]; then
    echo "\n\e[32m✅ MyBash updated"
  fi
}
