#!/bin/bash

# Get workspace info for git
getWorkspaceInfo() {
  local NAME=$(git config user.name)
  local EMAIL=$(git config user.email)
  local WORKSPACE=$(git config user.workspace)

  if [ -z "$EMAIL" ]; then
    echo "\e[41m Git is not initialized \e[0m"
  else
    echo "\e[36mℹ️ Git config info           \e[0m"
    echo "\e[36mName:     \e[0m $NAME"
    echo "\e[36mEmail:    \e[0m $EMAIL"
    echo "\e[36mWorkspace:\e[0m $WORKSPACE"
  fi
}
