#!/bin/bash

export ZSH="$MYBASH/zsh/oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="skaro" 
ZSH_THEME="af-magic" 

plugins=(git)

source $ZSH/oh-my-zsh.sh

# nvm-sh/nvm
export NVM_DIR="$MYBASH/node/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
